### ISSUE TITLE
Add option to declare headers or provide custom resty client to the API

### ISSUE THREAD

**Issue by Askadias** [MinterTeam/minter-go-sdk#1]
https://funfasy.dev/ requires 2 authentication headers to access its Minter API:
```
 'X-Project-Id' => '<YOUR-PROJECT-ID>',
 'X-Project-Secret' => '<YOUR-PROJECT-SECRET>',
```
Would be nice to have an option to specify customized resty.Client with predefined default headers

**Comment by klim0v** [comment]
@Askadias https://github.com/MinterTeam/minter-go-sdk/commit/e999ae6587388f10cc398ef762690b7190482e69
